-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:29:36 2019
-- Model: VLife Model    Version: 1.0

-- Modelo de Base de datos App VLife

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema VLife
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VLife` ;

-- -----------------------------------------------------
-- Schema VLife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VLife` ;
USE `VLife` ;

-- -----------------------------------------------------
-- Table `VLife`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Pais` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Provincias` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Provincias` (
  `idProvincias` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Nombre` VARCHAR(255) NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idProvincias`, `Pais_idPais`),
  INDEX `fk_Provincias_Pais1_idx` (`Pais_idPais` ASC) VISIBLE,
  CONSTRAINT `fk_Provincias_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `VLife`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Usuario` VARCHAR(255) NULL,
  `Clave` VARCHAR(255) NULL,
  `Coordenadas` VARCHAR(255) NULL,
  `Nombre` VARCHAR(255) NULL,
  `Apellido` VARCHAR(255) NULL,
  `Foto` VARBINARY(255) NULL,
  `Mail` VARCHAR(255) NULL,
  `Celular` VARCHAR(255) NULL,
  `Direccion` VARCHAR(255) NULL,
  `Ciudad` VARCHAR(255) NULL,
  `Provincias_idProvincias` INT NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Provincias_idProvincias`, `Pais_idPais`),
  INDEX `fk_Usuarios_Provincias1_idx` (`Provincias_idProvincias` ASC) VISIBLE,
  INDEX `fk_Usuarios_Pais1_idx` (`Pais_idPais` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Provincias1`
    FOREIGN KEY (`Provincias_idProvincias`)
    REFERENCES `VLife`.`Provincias` (`idProvincias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `VLife`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Profesionales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Profesionales` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Profesionales` (
  `idProfesionales` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Nombre` VARCHAR(255) NULL,
  `Apellido` VARCHAR(255) NULL,
  `Celular` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `IdProfEsp` INT NULL,
  `Coordenadas` VARCHAR(255) NULL,
  `Direccion` VARCHAR(255) NULL,
  `Ciudad` VARCHAR(255) NULL,
  `IdProvincia` INT NULL,
  `IdPais` INT NULL,
  `IdListaPrecio` INT NULL,
  `Foto` VARBINARY(255) NULL,
  `Reputacion` INT NULL,
  `Descripcion` MULTILINESTRING NULL,
  PRIMARY KEY (`idProfesionales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Especialidad` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Especialidad` VARCHAR(255) NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`ProfesionalEspecialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`ProfesionalEspecialidad` ;

CREATE TABLE IF NOT EXISTS `VLife`.`ProfesionalEspecialidad` (
  `idProfesionalEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `IdProfesional` INT NULL,
  `IdEspacialidad` INT NULL,
  PRIMARY KEY (`idProfesionalEspecialidad`),
  INDEX `fk_ProfesionalEspecialidad_Profesionales1_idx` (`IdProfesional` ASC) VISIBLE,
  INDEX `fk_ProfesionalEspecialidad_Especialidad1_idx` (`IdEspacialidad` ASC) VISIBLE,
  CONSTRAINT `fk_ProfesionalEspecialidad_Profesionales1`
    FOREIGN KEY (`IdProfesional`)
    REFERENCES `VLife`.`Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfesionalEspecialidad_Especialidad1`
    FOREIGN KEY (`IdEspacialidad`)
    REFERENCES `VLife`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Practica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Practica` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Practica` (
  `idPractica` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Practica` VARCHAR(255) NULL,
  `IdEspecialidad` INT NULL,
  `Precio` DOUBLE NULL,
  PRIMARY KEY (`idPractica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`ListaPrecios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`ListaPrecios` ;

CREATE TABLE IF NOT EXISTS `VLife`.`ListaPrecios` (
  `idListaPrecios` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `IdProfesional` INT NULL,
  `IdPractica` INT NULL,
  `Precio` DOUBLE NULL,
  `Fecha` DATETIME NULL,
  PRIMARY KEY (`idListaPrecios`),
  INDEX `fk_ListaPrecios_Profesionales1_idx` (`IdProfesional` ASC) VISIBLE,
  INDEX `fk_ListaPrecios_Practica1_idx` (`IdPractica` ASC) VISIBLE,
  CONSTRAINT `fk_ListaPrecios_Profesionales1`
    FOREIGN KEY (`IdProfesional`)
    REFERENCES `VLife`.`Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaPrecios_Practica1`
    FOREIGN KEY (`IdPractica`)
    REFERENCES `VLife`.`Practica` (`idPractica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Reputacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Reputacion` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Reputacion` (
  `idReputacion` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `IdProfesional` INT NULL,
  `IdUsuario` INT NULL,
  `Comentario` MULTILINESTRING NULL,
  `Like` INT NULL,
  PRIMARY KEY (`idReputacion`),
  INDEX `fk_Reputacion_Usuarios1_idx` (`IdUsuario` ASC) VISIBLE,
  INDEX `fk_Reputacion_Profesionales1_idx` (`IdProfesional` ASC) VISIBLE,
  CONSTRAINT `fk_Reputacion_Usuarios1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `VLife`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reputacion_Profesionales1`
    FOREIGN KEY (`IdProfesional`)
    REFERENCES `VLife`.`Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reputacion_Usuarios2`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `VLife`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reputacion_Usuarios3`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `VLife`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`RangoEdad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`RangoEdad` ;

CREATE TABLE IF NOT EXISTS `VLife`.`RangoEdad` (
  `idRangoEdad` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idRangoEdad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Solicitud` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Solicitud` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `IdUsuario` INT NULL,
  `IdProfesional` INT NULL,
  `IdPractica` INT NULL,
  `Fecha` DATE NULL,
  `Hora` DATETIME(6) NULL,
  `Comentario` VARCHAR(255) NULL,
  `Estado` INT NULL,
  PRIMARY KEY (`idSolicitud`),
  INDEX `fk_Solicitud_Usuarios_idx` (`IdUsuario` ASC) VISIBLE,
  INDEX `fk_Solicitud_Profesionales1_idx` (`IdProfesional` ASC) VISIBLE,
  INDEX `fk_Solicitud_Practica1_idx` (`IdPractica` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_Usuarios`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `VLife`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Profesionales1`
    FOREIGN KEY (`IdProfesional`)
    REFERENCES `VLife`.`Profesionales` (`idProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Practica1`
    FOREIGN KEY (`IdPractica`)
    REFERENCES `VLife`.`Practica` (`idPractica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VLife`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VLife`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `VLife`.`Pagos` (
  `idPagos` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NULL,
  `IdSolicitud` INT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `Monto` DOUBLE NULL,
  `FormaPago` VARCHAR(255) NULL,
  `Estado` INT NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  PRIMARY KEY (`idPagos`, `Solicitud_idSolicitud`),
  INDEX `fk_Pagos_Solicitud1_idx` (`Solicitud_idSolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_Pagos_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `VLife`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
