version: 2.1
orbs:
    aws-cli: circleci/aws-cli@0.1.16
jobs:
    build:
        working_directory: ~/circleci-breeze-cms
        docker:
            - image: circleci/node:9.0 # the primary container, where your job's commands are run
        steps:
            - run: echo "Run your code here"
            - run: |
                  sudo apt-get update && apt-get upgrade -y
                  sudo apt-get install -y python-dev python-pip
                  sudo pip install awscli
            - run: |
                  aws -v
