version: 2.1

orbs:
    aws-cli: circleci/aws-cli@0.1.16

jobs:
    aws-cli-example:
        executor: aws-cli/default
        steps:
            - checkout
            - aws-cli/install
            - run:
                  name: Configure AWS Access Key ID
                  command: |
                      aws configure set aws_access_key_id \ $AWS_ACCESS_KEY_ID \
            - run:
                  name: Configure AWS Secret Access Key
                  command: |
                      aws configure set aws_secret_access_key \ $AWS_SECRET_ACCESS_KEY \
            - run:
                  name: Check AWS Config
                  command: |
                      aws sts get-caller-identity
            - run: echo "Run your code here"

workflows:
    version: 2
    aws-cli:
        jobs:
            - aws-cli-example:
                  context: aws
