version: 2.1

orbs:
    aws-cli: circleci/aws-cli@0.1.16

jobs:
    aws-cli-example:
        executor: aws-cli/default
        steps:
            - checkout
            - aws-cli/install
            - run: |
                  aws configure set aws_access_key_id \ $AWS_ACCESS_KEY_ID \
            - run: echo "Run your code here"

workflows:
    version: 2
    aws-cli:
        jobs:
            - aws-cli-example:
                  context: aws
